### ISSUE TITLE
save Megatron-LM MOE model error with flash checkpoint

### ISSUE THREAD

**Issue by TING2938** [intelligent-machine-learning/dlrover#1030]
Megatron-LM use separate optimizers for expert parameters and non-expert parameters, so it will be wrong when using distributed optimizer.
Can you fix it?  thanks

https://github.com/NVIDIA/Megatron-LM/blob/89574689447d694bb19dd86fc8a6153b4467ba9d/megatron/core/optimizer/__init__.py#L195

![image](https://github.com/intelligent-machine-learning/dlrover/assets/43649849/f9694ae9-9041-4c34-857c-77206250bd28)

**Comment by workingloong** [comment]
Thanks for your feedback, we will fix it with our best effort.

**Comment by workingloong** [comment]
Flash Checkpoint has support Megatron-LM MOE model in the commit[ cb995d5](https://github.com/NVIDIA/Megatron-LM/commit/cb995d571faea19d01a1bf55ed0fd89523b9ce64) in Megatron-LM. You can pull the master branch of DLRover  and build a package to test it.

If you are using the latest master branch of Megatron-LM, you need to modify the following line to `from megatron.core.optimizer.optimizer import ChainedOptimizer`. Because, Megatron-LM has changed the position of optimizer.

https://github.com/intelligent-machine-learning/dlrover/blob/master/dlrover/trainer/torch/flash_checkpoint/megatron_dist_ckpt.py#L40
