### ISSUE TITLE
When the checkpoint is cached in shm, will there be an OOM exception if the checkpoint is too large？

### ISSUE THREAD

**Issue by jokerwenxiao** [intelligent-machine-learning/dlrover#941]

**Comment by workingloong** [comment]
An OOM error may happen but rarely happen in a training job with GPUs for the following reasons:
- The CPU RAM is much cheaper than GPU HBM. and we usually configure more RAM than GPU HBM. For example, [the GPU server gn7e on AliYun](https://developer.aliyun.com/article/1277458) has 125GB RAM for each A100-80GB.
- The size of checkpoint is a part of the used CUDA memory of the training. The used CUDA memory of the training contains the model parameters (model weights + optimizer states + gradients).  activations and fragments. The checkpoint only contains the model weights and optimizer states. For example, the llama2-65B has 120GB  model parameters and 142GB activations when batch size is 1, refers to the [blog](https://zhuanlan.zhihu.com/p/648924115). If the batch size increases, the ratio of model memory will descrease because the activation size is proportational to the batch size and the size of model parameters are fixed. For example, If we use 8 nodes with A100*8 to train the llama2-65B with FSDP or DeepSpeed Zero, each node only has 120GB/8=15GB model parameters and only need 15GB shm to checkpoint.

**Comment by jokerwenxiao** [comment]
got it!

**Comment by jokerwenxiao** [comment]
> An OOM error may happen but rarely happen in a training job with GPUs for the following reasons:
> 
> * The CPU RAM is much cheaper than GPU HBM. and we usually configure more RAM than GPU HBM. For example, [the GPU server gn7e on AliYun](https://developer.aliyun.com/article/1277458) has 125GB RAM for each A100-80GB.
> * The size of checkpoint is a part of the used CUDA memory of the training. The used CUDA memory of the training contains the model parameters (model weights + optimizer states + gradients).  activations and fragments. The checkpoint only contains the model weights and optimizer states. For example, the llama2-65B has 120GB  model parameters and 142GB activations when batch size is 1, refers to the [blog](https://zhuanlan.zhihu.com/p/648924115). If the batch size increases, the ratio of model memory will descrease because the activation size is proportational to the batch size and the size of model parameters are fixed. For example, If we use 8 nodes with A100*8 to train the llama2-65B with FSDP or DeepSpeed Zero, each node only has 120GB/8=15GB model parameters and only need 15GB shm to checkpoint.

got it!
