### ISSUE TITLE
Why is the ATorch RLHF solution so similar to the open source OpenRLHF ?

### ISSUE THREAD

**Issue by hijkzzz** [intelligent-machine-learning/dlrover#966]
https://mp.weixin.qq.com/s/reNK0ASYDvPhIUTz6iBhuQ

Last November, OpenRLHF had already integrated vLLM and Ray-based distributed RLHF solutions into its repository, garnering hundreds of stars. The 70B+ RLHF optimization solution was even discussed and shared within the OpenLLMAI community before last August. Why is the ATorch RLHF solution released in recent days so similar to OpenRLHF's (also based on vLLM + distributed RLHF), despite slight differences in implementation details? The PR seems to claim originality.

OpenRLHF 去年11月就将 vLLM 和基于 Ray 的分布式 RLHF 方案完整合并到仓库，并且已经获得几百stars
70B+RLHF优化方案更是在去年8月份之前就在 OpenLLMAI 社区讨论分享
为什么这几天才发布的 ATorch RLHF 的方案和 OpenRLHF 如此相似（同样基于 vLLM + 分布式RLHF模块），尽管实现细节略有不同，却在宣传文中似乎号称为原创。

**Comment by hxdtest** [comment]
首先感谢您的关注，ATorch 是蚂蚁内部LLM训练真实使用的项目，ATorch RLHF 23年5月开始立项设计，23年8月内部就已经开始使用，24年初我们决定将其开源。时间线上，我们并没有机会参考您的项目，当时主要参考对象是更出名的deepspeed chat和trlx。

所以您认为两者similar的依据是两者都是使用了vllm和所谓的使用了ray么？
1. ATorch RLHF并未直接使用Ray。
训练部分采用K8s pod调度 + torch.distributed.run启动训练进程，使用pod调度+torch.distributed.run启动主要是和dlrover调度/容错/弹性适配；如果vllm独立部署，vllm的worker由ray启动，此处用到ray是vllm内部机制。 如果用其他的backend，启动方式由特定的backend决定。 

2. 关于使用vllm：
我们的方案是训练-推理接耦+高性能推理backend+权重同步+数据分发。vllm是一个可选的backend，也可以使用tgi/onnx_runtime，或者未来有其他可用高性能推理后端，也可以接入。关于vllm使用方法：10B量级，我们支持vllm和训练在同一个进程中共享权重；70B量级，我们支持仅同步部分训练权重，且vllm和训练worker并不在一个process group。在开发实现方案时，主要参考了deepspeed和meta的方案，上述调研内容在微信公众号中也列出来，当时并未参考OpenRLHF。
开源社区活跃发展，相似的解决方案可以独立出现，两个都使用了vllm，但是两者并不similar。（vllm不是咱们任何一方发明的，不能说使用了一个第三方库就算抄袭，这说不通）

3. 我们高度欣赏OpenRLHF项目，后续也会考虑加入分析对比，也欢迎加入DLRover dingding交流群（ID：31525020959）进行更深入的技术交流。

Thank you for your attention. ATorch is a project actually used for LLM training within Ant Group. It was initiated and designed in May 2023, and by August 2023, it was already being used internally. At the beginning of 2024, we decided to open source it. On the timeline, we had no opportunity to refer to your project; at that time, our main references were the more famous deepspeed chat and trlx.
So, do you believe the two are similar because both used vllm and so-called Ray?
1. ATorch RLHF does not directly use Ray. For training, we used K8s pod scheduling + torch.distributed.run to launch training processes. The use of pod scheduling + torch.distributed.run is mainly to adapt to dlrover's scheduling, fault tolerance, and elasticity. If vllm is deployed independently, its workers are launched by Ray; this is an internal mechanism of vllm. If another backend is used, the launching method is determined by the specific backend.
2. Regarding the use of vllm: Our approach is training-inference decoupling + high-performance inference backend + weight synchronization + data distribution. vllm is an optional backend, which can also be replaced by tgi/onnx_runtime or other available high-performance inference backends in the future. Regarding the use of vllm: for the 10B scale, we support sharing weights between vllm and training within the same process; for the 70B scale, we support only synchronizing part of the training weights, and the vllm and training workers are not in the same process group. During the development of our solution, we mainly referred to the approaches of deepspeed and Meta. The above research content is also listed in our WeChat official account, and we did not refer to OpenRLHF at the time.
The open-source community is actively developing, and similar solutions can emerge independently. Both projects may have used vllm, but that doesn't make them similar. (vllm is not invented by any of us, and using a third-party library cannot be considered plagiarism, that makes no sense.)
1. You are welcome to join a more in-depth technical exchange on DingDing (ID: 31525020959).

**Comment by YixinSong-e** [comment]
请问Atorch RLHF的代码具体在哪个路径呢，我想学习一下～

**Comment by workingloong** [comment]
> 请问Atorch RLHF的代码具体在哪个路径呢，我想学习一下～

这个代码才提 PR，你可以看这个 PR #968

**Comment by hxdtest** [comment]
> 请问Atorch RLHF的代码具体在哪个路径呢，我想学习一下～

我们参考trlx定义了一套训练流程。后来也解决了deepspeed hybrid engine中的一些bug，支持ds hybrid engine作为我们运行的基线。

关于rlhf训练流程可以参考deepspeed chat。其中deepspeed hybrid engine 还是存在问题，例如tp切分等问题，具体可以在deepspeed examples仓库目录下搜索相关issuse，我们对齐进行了修复。

和微信公共号中介绍的相关的功能点： 

1.  `atorch/atorch/rl/inference_backend/vllm_backend.py`
对于共享权重方式，我们会vllm在启动后设置vllm module权重为空，推理时设置vllm的权重为训练权重，此处需要解决vllm和训练进程在同一个进程中创建process groupd的问题。

不共享情况下，会通过网络通信发送训练部分权重。此处不通过torch组网，而是通过自己实现的通信module。
2.  `atorch/atorch/tests/rl_tests/rl_ds_llama2_inference_test.py`
共享权重最小测试用例

3.  `atorch/atorch/tests/rl_tests/rl_redis_test.py
70B场景下，推理实例生成prompt-response，写入到redis队列。训练实例通过redis 队列的dataloader，从redis队列拿训练数据。两者可以解耦。

4. 我们对vllm也进行了修改，支持热更新权重、共享权重、和训练进程共存，后续我们将以镜像的形式对外提供可以运行的环境和最小端到端运行例子。

**Comment by YixinSong-e** [comment]
非常感谢你们的回复～
